language: cpp

cache: ccache

dist: focal

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++ CCOMPILER=gcc PUSH_COVERAGE=ON TRAVIS_BUILD_DOCS=ON
    - COMPILER=g++-8 CCOMPILER=gcc-8
    - COMPILER=g++-10 CCOMPILER=gcc-10
    - COMPILER=clang++ CCOMPILER=clang
  global:
    - secure: "CQRYHWlg/WDu5DBUeDwGo+rPeOofN08DhiLUNlLtZjMWaRyP0Cop1qVaFs8ESOkYiWek2MdpvjZud+7hL+yx2ogvNx4SfHpUMCDKYgcX+YQ9MmYwabvoKq8N6KVXE3lbPp549TonHdDuNCWNKRniNjYtrij5J+IiIiT8/6Txo2p9RWk6YSUTdXJ9YrfuWMtRuF5uo9SHGyujv8pOJKedrwWoSBbHT44jnwfHMVe/C8jgjwlrJ9N3iXOtsG6sj+UTS8vOpL+jpBONEbBfHgSFU57I7IFNdPQbSObpVwG9geOAHT7IQQyQ9hp2AJoFxxVURB5SzqztDDpQ0XIF76vuH9tA/fF2pwDsLRmcLR8JU1TCmQgvnlYD0+Or9S1Dq0tQME5AP+21Hk2zVcGdbgQP7XWix758F0vpOXa4PXw8TmAjP2jKyAMHlzR3icr3+OmKSK3uXMMt2HSMOJQ+JvFxr//DM493i/VGyeY25/zu3A9RstiE+1d82Fi9xKOmMf4smvSkjOgT0b727jqNbNe6CvEKQUmqHabzYRQzUVz6WPVDHBxZP7AiKmZIVQXYnDsVXywStkSoxxY5En6XKpq0GR3bIVtUMORgZPoZi7Jni+/4EckcYH8g9mpsQf9tPRcOZ2WIvt5gqp2MZuwBLBRcbxihuECfBscqdeA0oDU5AZw="
    - GH_REPO_NAME: crow
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/mrozigor/crow.git

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-precise
    packages:
      - g++
      - g++-8
      - g++-10
      - clang
      - libboost-all-dev
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - if [ "$PUSH_COVERAGE" == "ON" ]; then pip install --user cpp-coveralls; fi

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script: make -j2 && ctest -V -j2

after_success:
  - cd ..
  - if [ "$PUSH_COVERAGE" == "ON" ]; then coveralls -i include --gcov-options '\-lp'; fi
  - chmod +x generateDocumentationAndDeploy.sh
  - test "$TRAVIS_BRANCH" = "master" && test $TRAVIS_PULL_REQUEST = "false" && test "$TRAVIS_BUILD_DOCS" = "ON" && ./generateDocumentationAndDeploy.sh
