language: cpp

cache: ccache

dist: focal


compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++ CCOMPILER=gcc PUSH_COVERAGE=ON
    - COMPILER=g++-8 CCOMPILER=gcc-8
    - COMPILER=g++-10 CCOMPILER=gcc-10
    - COMPILER=clang++ CCOMPILER=clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-precise
    packages:
      - g++
      - g++-8
      - g++-10
      - clang
      - libboost-all-dev

install:
  - if [ "$PUSH_COVERAGE" == "ON" ]; then pip install --user cpp-coveralls; fi

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script: make -j2 && ctest -V -j2

after_success:
  - cd ..
  - if [ "$PUSH_COVERAGE" == "ON" ]; then coveralls -i include --gcov-options '\-lp'; fi
